### ISSUE TITLE
Pre-compiled binaries for older macOS versions

### ISSUE THREAD

**Issue by dnaka91** [terhechte/postsack#27]
Very cool project, and I just wanted to try it out (without pulling the repo and compiling myself). Sadly, the pre-compiled macOS binary only seems to work for macOS 12 (Monterey) and later.

It would be great if you can provide pre-compiled binaries that work on older versions too.

I see you already set the [`osx_minimum_system_version`](https://github.com/terhechte/postsack/blob/456424cba845382b676112a4e008ae9202d5e683/postsack-native/Cargo.toml#L17) to `10.14`, but it seems that didn't have the desired effect or was it maybe added after the initial release was made?

**Comment by terhechte** [comment]
Hey, I'll investigate this. In theory the app should be compatible with earlier versions, so I guess I'm messing something up during the build. Thanks for pointing it out.

**Comment by terhechte** [comment]
I think I managed to solve this. The related PR is here https://github.com/terhechte/postsack/pull/30.

I'll do some more testing, merge this a bit later, and then create a new release.

**Comment by terhechte** [comment]
@dnaka91 You can find the new release here https://github.com/terhechte/postsack/releases/tag/v1.0.1

**Comment by dnaka91** [comment]
Thanks for the quick action 🚀

I'll give it a try later today and close the issue if it works. Actually compiled it myself in the meantime and played around with it a bit. Great app 👍
